try {
    console.log(num);
}
catch {
    console.log("Error occured!....");
}
finally {
    console.log("File closed");
}